# Generated by Django 4.1.7 on 2023-02-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplyManager', '0003_alter_thewall_taskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thewall',
            name='profile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thewall',
            name='section',
            field=models.IntegerField(default=0),
        ),
    ]
