# Generated by Django 4.1.7 on 2023-02-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplyManager', '0004_alter_thewall_profile_alter_thewall_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.IntegerField(default=0)),
                ('section', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
                ('ice', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
            ],
        ),
    ]
